### ISSUE TITLE
Code signing problem

### ISSUE THREAD

**Issue by d029940** [bsupnik/bricksmith#13]
As soon as I let XCode13 migrate the project files (*.xcodeproj)  and let code signing checked, I cannot build the project (Trunk version of Bricksmith).
No problems building subproject LSynth and AMSProgressBar. But the Bricksmith project  cannot be built - no matter if you use "Sign locally" or "Developer Id"

I figured out that the culprit is "lsynth.mpd", which will be copied to the executable as the last step in "Build Phases - Copy LSynth". It also does not matter if you check "Code sign on copy" on or off.

Here is the output of the build phase:

> CodeSign /Users/manfred/Library/Developer/Xcode/DerivedData/Bricksmith-bzbzgqtquajathcgvfbzshquszvq/Build/Products/Debug/Bricksmith.app (in target 'Bricksmith' from project 'Bricksmith')

    cd /Users/manfred/Developer/XCode/Lego/bricksmithMK/trunk/Bricksmith
    export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

    
    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - --entitlements /Users/manfred/Library/Developer/Xcode/DerivedData/Bricksmith-bzbzgqtquajathcgvfbzshquszvq/Build/Intermediates.noindex/Bricksmith.build/Debug/Bricksmith.build/Bricksmith.app.xcent --timestamp\=none --generate-entitlement-der /Users/manfred/Library/Developer/Xcode/DerivedData/Bricksmith-bzbzgqtquajathcgvfbzshquszvq/Build/Products/Debug/Bricksmith.app

> /Users/manfred/Library/Developer/Xcode/DerivedData/Bricksmith-bzbzgqtquajathcgvfbzshquszvq/Build/Products/Debug/Bricksmith.app: code object is not signed at all
In subcomponent: /Users/manfred/Library/Developer/Xcode/DerivedData/Bricksmith-bzbzgqtquajathcgvfbzshquszvq/Build/Products/Debug/Bricksmith.app/Contents/MacOS/lsynth.mpd

I can only build the whole project if I switch code signing for the Bricksmith project completely off (s. attached file).

![Bricksmith codesigning problem](https://user-images.githubusercontent.com/17231838/148931939-185d7063-81a7-4e8d-9556-6d37920fc6ec.png)

**Comment by allenmonroesmith** [comment]
Code signing isn't supposed to be enabled. I don't have a Mac developer account, and I've no plan to get one either.

I've used Xcode 13 and didn't have this problem—did you let it fix the project settings warning that I haven't braved trying yet?

**Comment by d029940** [comment]
Yes I let fix the project settings.
You can either sign ist locally or with a developer id or with a paid developer account. I do not have the paid account either.
But you can sign it (for whatever reason) without having a paid Developer Apple Account. Signing is done automatically if you migrate the project settings as proposed by Xcode 13 leaving all migration steps on. That is what I did because I thought I should follow Apple recommendations. (We you shouldn't do it blindly).
So these are the options:
- Migrate to new project settings but check off the code signing steps OR
- Migrate to new project settings leaving everything checked on and got to the project settings afterwards and delete the code signing identity (S. picture) OR
- Do not migrate the project settings OR
- we need to find a solution for copying lsynth.mpd which prevents to sign the Bricksmith project

**Comment by d029940** [comment]
Attached you will find a suggestion to read the file lsynth.mpd from the program. Just a small change in LDrawSynth.m.
Here is the code for copying:

`    if ([configPath length] == 0) {
        configPath = [[NSBundle mainBundle] pathForResource:@"lsynth" ofType:@"mpd"];
    }`

<img width="1051" alt="Screenshot 2022-02-15 at 14 04 09" src="https://user-images.githubusercontent.com/17231838/154067681-ccb8e087-2771-44eb-bfcb-2152ab4a2b3e.png">

This modification enables us to get rid of copying lsynth.mpd in the build phases of the Bricksmith project target. 

Hence the project can be signed locally,  with a personal developer account or with a paid account.

As far as I read from the internet, signing is mandatory, if you want to use Xcode Instruments to check for allocations. I think this is a valid tool for checking memory leaks, especially when we are starting to convert to ARC.

Please correct me, if I am mistaken.
