### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by scontini76** [bsupnik/bricksmith#2]
Hi,

I saw that on SourceForge the project is quite abandoned. Is this the place to keep this software alive?

**Comment by bsupnik** [comment]
Yes - the project is still in a bit of trouble because Apple has changed the scrolling tech inside AppKit and no one has updated BrickSmith - I can probably produce a binary that will work for now but we are reaching a point where without new code no one will be able to compile a working app.

**Comment by allenmonroesmith** [comment]
And it's alive now!
